name: Lab 3 Performance Pipeline
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run HTMLHint
        run: |
          npm install -g htmlhint
          htmlhint "*.html" || true

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          IMAGE_NAME_LOWER=$(echo "ghcr.io/${{ github.actor }}/software_engineering" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME_LOWER:latest .
          docker push $IMAGE_NAME_LOWER:latest

  performance-tests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Container
        run: |
          IMAGE_NAME_LOWER=$(echo "ghcr.io/${{ github.actor }}/software_engineering" | tr '[:upper:]' '[:lower:]')
          docker pull $IMAGE_NAME_LOWER:latest
          docker run -d --name web_site -p 80:80 $IMAGE_NAME_LOWER:latest
          sleep 10

      - name: Run k6 Smoke Test
        run: docker run --rm --network host -v $(pwd)/tests:/scripts grafana/k6 run /scripts/smoke_test.js

      - name: Run k6 Load Test
        run: docker run --rm --network host -v $(pwd)/tests:/scripts grafana/k6 run /scripts/load_test.js

      - name: Run k6 Stress Test
        run: docker run --rm --network host -v $(pwd)/tests:/scripts grafana/k6 run /scripts/stress_test.js